services:
  - type: web
    name: whitegod-portfolio
    env: node
    plan: free
    buildCommand: npm --prefix server install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_ORIGIN
        value: "*"
      - key: NOTIFICATION_EMAIL
        value: ayush.singh.10293@gmail.com
      - key: MONGO_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
